### PR TITLE
fix 150245 pattern replace

### PR DESCRIPTION
**Pull request by nrnhines**
The change in random for 150245 changed the number of spikes which requires a change in a pattern replace line in modeldb-run.yaml

### CODE REVIEW

**Review by pramodk — APPROVED** [review]

**Comment by pramodk** [comment]
@nrnhines : CI is still failing?

**Comment by nrnhines** [comment]
> @nrnhines : CI is still failing?

I'm not sure what is failing. Perhaps it has to do with neuronsimulator/nrn#2764 not yet being merged.

**Comment by nrnhines** [comment]
> @nrnhines : CI is still failing?

I'm afraid I'm at a loss. 138379 is working on my machine (it is one of the models that needed Random123 changes) and the change I made to ```modeldb-run.yaml``` is present in this PR.
```
138379:
    github: "pull/3"
    ...
```
$ nrniv --version
NEURON -- VERSION 8.2.4 HEAD (1d87d5d39) 2024-02-09
$ runmodels --workdir temp8.2.4 --clean --virtual --gout 138379
```
```
$ nrniv --version
NEURON -- VERSION 9.0a-170-ged09605ab master (ed09605ab) 2024-02-26
$ runmodels --workdir temp1 --clean --virtual --gout 138379
```
```
$ diffreports2html temp8.2.4.json temp1.json
Writing /home/hines/neuron/nrn-modeldb-ci/temp8.2.4-vs-temp1.html ...
Done.
Writing /home/hines/neuron/nrn-modeldb-ci/runtimes-temp8.2.4-vs-temp1.html ...
Done.
```

**Comment by nrnhines** [comment]
Found it in the artifacts.
image
So I guess another pattern/replace line is needed to get rid of the Matplotlib line.

**Comment by nrnhines** [comment]
> So I guess another pattern/replace line is needed to get rid of the Matplotlib line.

Or would it be better to install the Matplotlib font cache during setup? How would that be done?

**Pull request merged**
