### PR TITLE
`runmodels`: add `--norun` option

### LINKED ISSUE #31: Build only (with no run) for Windows debugging.
I'm playing with the additional option for runmodels
```
+        --norun                 Compile and link. Success if nrnivmodl succeeds. (Useful for Windows when debugging incomplete g++ toolchain in installer.)
```
and am at the point where it seemed simplest to force every model to effectively have the yaml property ```run: null```.
I tried:
```
 class ModelRun(dict):
-    def __init__(self, model, working_dir, clean=False):
+    def __init__(self, model, working_dir, clean=False, norun=False):
```
to merely
```
-        self._fetch_model()
+        if not norun:
+            self._fetch_model()
```
but I guess ```_fetch_model()``` is getting more than just ```run```.
I'm wondering if someone can short circuit my guesswork by suggesting how to effectively replace the ```run``` after return from ```_fetch_model()```.

### PR DESCRIPTION
**Pull request by alexsavulescu**
* compile and link only

Closes #31 

Note I have only done some sanity checking (didn't run all models)

### CODE REVIEW

**Comment by alexsavulescu** [comment]
> Note I have only done some sanity checking (didn't run all models)

running here: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/2453365351

**Review by nrnhines — APPROVED** [review]
Perfect. Thanks!  On my linux desktop, my foo.json begins with
```
{
    "0": {
        "NEURON version": "8.2a-102-g3e9286d95",
        "Stats": {
            "Failed models": {
                "Accession numbers": [
                    97868
                ],
                "Count": 1
            },
            "Failed runs": {
                "Accession numbers": [],
                "Count": 0
            },
            "Skipped runs": {
                "Accession numbers": [
                    22203,
                    53435,
                    53965,
                    83319,
                    87473,
                    149174,
                    223962,
                    260971
                ],
                "Count": 8
            },
            "Total nof models run": 680
        }
    },
```
and my problem with 97868 apparently is that I don't have mysql installed. (figuring out things like that is the whole point of the ```--norun``` for windows.)  I'll have to think about the purpose of the ```"Skipped runs": {``` to understand why we left those out of at least building the ```special```.  By the way, when trying again, I generally just precede with ```rm -r -f foo*``` instead of a ```--clean```.

**Comment by alexsavulescu** [comment]
> I'll have to think about the purpose of the `"Skipped runs":`

I remember some of those were because the simulation was taking too long. So I curated a few and enabled them. The rest didn't have any comments or were not straightforward to shorten, therefore still skipped.

**Comment by alexsavulescu** [comment]
i.e. https://github.com/neuronsimulator/nrn-modeldb-ci/blob/master/modeldb/modeldb-run.yaml#L414

**Comment by alexsavulescu** [comment]
I have run locally all models with `--norun` and did not spot any issue. Will merge.

**Pull request merged**
